import os
import time
import zipfile
import shutil
from pathlib import Path
from typing import Optional, Callable, Dict, Any, Union, List
from dataclasses import dataclass
from urllib.parse import quote
import requests


@dataclass
class WorkflowFile:
    """Represents a file generated by a workflow."""
    id: int
    name: str
    size: int
    content_type: str


@dataclass
class WorkflowTask:
    """Represents a workflow task."""
    id: str
    workflow_id: str
    status: str  # 'in_progress', 'completed', 'failed', 'canceled'
    result: Optional[Any] = None
    files: Optional[List[WorkflowFile]] = None
    error: Optional[str] = None
    started_at: Optional[str] = None
    completed_at: Optional[str] = None
    created_at: Optional[str] = None


@dataclass
class WorkflowResult:
    """Result of running a workflow, with helpers to download generated files."""
    result: Any
    task: WorkflowTask
    _api_key: str
    _api_url: str

    def download_file(self, file_id: int, dest_path: str) -> None:
        """
        Downloads a file from the workflow task.
        
        Args:
            file_id: The ID of the file to download (from task.files[].id)
            dest_path: The destination path to save the file
        """
        download_workflow_file(
            api_key=self._api_key,
            api_url=self._api_url,
            task_id=self.task.id,
            file_id=file_id,
            dest_path=dest_path
        )

    def download_all_files(self, dest_dir: str) -> None:
        """
        Downloads all files from the workflow task to a directory.
        
        Args:
            dest_dir: The destination directory to save the files
        """
        if not self.task.files:
            return

        dest_path = Path(dest_dir)
        dest_path.mkdir(parents=True, exist_ok=True)

        for file in self.task.files:
            # Sanitize filename to prevent path traversal attacks
            safe_name = Path(file.name).name
            file_dest = dest_path / safe_name
            self.download_file(file.id, str(file_dest))


def run_workflow(
    database: str,
    workspace: str,
    workflow: str,
    api_key: Optional[str] = None,
    api_url: str = "https://fabricate.tonic.ai/api/v1",
    params: Optional[Dict[str, Any]] = None,
    on_progress: Optional[Callable[[Dict[str, str]], None]] = None,
) -> WorkflowResult:
    """
    Runs a workflow and waits for the result.
    
    Args:
        database: The name of the database (required)
        workspace: The workspace to use (required)
        workflow: The name of the workflow to run (required)
        api_key: The API key for authentication. Defaults to FABRICATE_API_KEY env var.
        api_url: The API URL. Defaults to https://fabricate.tonic.ai/api/v1
        params: Optional parameters to pass to the workflow
        on_progress: Optional progress callback function receiving {'status': str, 'message': str}
        
    Returns:
        WorkflowResult containing the result, task, and file download methods
        
    Raises:
        ValueError: If required parameters are missing
        Exception: If workflow execution fails
    """
    # Get API key from parameter or environment
    if api_key is None:
        api_key = os.environ.get('FABRICATE_API_KEY')

    # Validate required parameters
    if not api_key:
        raise ValueError('api_key is required')

    if not database:
        raise ValueError('database is required')

    if not workspace:
        raise ValueError('workspace is required')

    if not workflow:
        raise ValueError('workflow is required')

    if params is None:
        params = {}

    headers = {'Authorization': f'Bearer {api_key}'}
    url = (
        f'{api_url}/workspaces/{quote(workspace, safe="")}'
        f'/databases/{quote(database, safe="")}'
        f'/workflows/{quote(workflow, safe="")}'
    )

    try:
        response = requests.post(url, json=params, headers=headers)
        response.raise_for_status()
        data = response.json()
    except requests.exceptions.HTTPError as e:
        if e.response is not None and 'application/json' in e.response.headers.get('content-type', ''):
            error_data = e.response.json()
            raise Exception(error_data.get('error', str(e)))
        else:
            raise

    task_id = data.get('task_id')
    status = data.get('status', '')

    if not task_id:
        raise Exception('No task_id returned from API')

    if on_progress:
        on_progress({'status': status, 'message': 'Workflow started'})

    # Poll for completion
    task = _poll_workflow_task(task_id, api_url, api_key, on_progress)

    if task.error:
        raise Exception(task.error)

    return WorkflowResult(
        result=task.result,
        task=task,
        _api_key=api_key,
        _api_url=api_url
    )


def _poll_workflow_task(
    task_id: str,
    api_url: str,
    api_key: str,
    on_progress: Optional[Callable[[Dict[str, str]], None]] = None
) -> WorkflowTask:
    """
    Polls the workflow task API until the task is completed.
    
    Args:
        task_id: The ID of the task to poll
        api_url: The API URL
        api_key: The API key
        on_progress: Optional progress callback
        
    Returns:
        The completed WorkflowTask
        
    Raises:
        Exception: If task fails or is canceled
    """
    headers = {'Authorization': f'Bearer {api_key}'}

    while True:
        response = requests.get(
            f'{api_url}/workflow_tasks/{task_id}',
            headers=headers
        )
        response.raise_for_status()
        data = response.json()

        task = _parse_workflow_task(data)

        if task.status == 'completed':
            if on_progress:
                on_progress({'status': 'completed', 'message': 'Workflow completed'})
            return task
        elif task.status == 'failed':
            raise Exception(task.error or 'Workflow failed')
        elif task.status == 'canceled':
            raise Exception('Workflow was canceled')
        else:
            if on_progress:
                on_progress({'status': task.status, 'message': 'Workflow running...'})
            time.sleep(1)


def _parse_workflow_task(data: Dict[str, Any]) -> WorkflowTask:
    """Parses a workflow task from API response data."""
    files = None
    if data.get('files'):
        files = [
            WorkflowFile(
                id=f['id'],
                name=f['name'],
                size=f['size'],
                content_type=f['content_type']
            )
            for f in data['files']
        ]

    return WorkflowTask(
        id=data['id'],
        workflow_id=data.get('workflow_id', ''),
        status=data['status'],
        result=data.get('result'),
        files=files,
        error=data.get('error'),
        started_at=data.get('started_at'),
        completed_at=data.get('completed_at'),
        created_at=data.get('created_at')
    )


def download_workflow_file(
    task_id: str,
    file_id: int,
    dest_path: str,
    api_key: Optional[str] = None,
    api_url: str = "https://fabricate.tonic.ai/api/v1",
) -> None:
    """
    Downloads a file from a workflow task.
    
    Args:
        task_id: The ID of the workflow task
        file_id: The ID of the file to download
        dest_path: The destination path to save the file
        api_key: The API key for authentication. Defaults to FABRICATE_API_KEY env var.
        api_url: The API URL. Defaults to https://fabricate.tonic.ai/api/v1
        
    Raises:
        ValueError: If required parameters are missing
        requests.HTTPError: If download fails
    """
    # Get API key from parameter or environment
    if api_key is None:
        api_key = os.environ.get('FABRICATE_API_KEY')

    if not api_key:
        raise ValueError('api_key is required')

    if not task_id:
        raise ValueError('task_id is required')

    if not file_id:
        raise ValueError('file_id is required')

    if not dest_path:
        raise ValueError('dest_path is required')

    # Ensure the directory exists
    dest_file = Path(dest_path)
    dest_dir = dest_file.parent

    if dest_dir != Path('.') and not dest_dir.exists():
        dest_dir.mkdir(parents=True, exist_ok=True)

    url = f'{api_url}/workflow_tasks/{task_id}/{file_id}/download'
    headers = {'Authorization': f'Bearer {api_key}'}

    try:
        with requests.get(url, headers=headers, stream=True) as response:
            response.raise_for_status()
            with open(dest_path, 'wb') as f:
                for chunk in response.iter_content(chunk_size=8192):
                    f.write(chunk)
    except Exception:
        # Clean up partial file on error
        if dest_file.exists():
            dest_file.unlink()
        raise


def generate(
    api_key: Optional[str] = None,
    api_url: str = "https://fabricate.tonic.ai/api/v1",
    database: Optional[str] = None,
    workspace: Optional[str] = None,
    entity: Optional[str] = None,
    format: Optional[str] = None,
    overrides: Optional[Dict[str, Any]] = None,
    on_progress: Optional[Callable[[Dict[str, Any]], None]] = None,
    dest: Optional[str] = None,
    unzip: bool = True,
    overwrite: bool = False,
    connection: Optional[Dict[str, Any]] = None,
) -> None:
    """
    Generates data for a given database.
    
    Args:
        api_key: The API key for authentication. Defaults to FABRICATE_API_KEY env var.
        api_url: The API URL. Defaults to https://fabricate.tonic.ai/api/v1
        database: The name of the database to generate (required)
        workspace: The workspace to use (required)
        entity: Optional single entity/table to generate
        format: The output format (sql, sqlite, csv, jsonl, xml)
        overrides: Optional override parameters
        on_progress: Optional progress callback function
        dest: Destination path for downloaded files (required unless connection provided)
        unzip: Whether to unzip downloaded files (default: True)
        overwrite: Whether to overwrite existing destination (default: False)
        connection: Database connection details for direct push
        
    Raises:
        ValueError: If required parameters are missing or invalid
        requests.HTTPError: If API requests fail
        Exception: If task execution fails
    """
    # Get API key from parameter or environment
    if api_key is None:
        api_key = os.environ.get('FABRICATE_API_KEY')
    
    # Validate required parameters
    if not api_key:
        raise ValueError('api_key is required')
    
    if not database:
        raise ValueError('database is required')
    
    if not workspace:
        raise ValueError('workspace is required')
    
    if not format and not connection:
        raise ValueError('format or connection is required')
    
    if format and connection:
        raise ValueError('format and connection cannot both be provided')
    
    if not dest and not connection:
        raise ValueError('dest is required unless connection is provided')
    
    if dest and Path(dest).exists() and not overwrite:
        raise ValueError('dest already exists')
    
    # Create the generation task
    headers = {'Authorization': f'Bearer {api_key}'}
    payload = {
        'format': format,
        'connection': connection,
        'database': database,
        'entity': entity,
        'overrides': overrides,
        'workspace': workspace
    }
    
    try:
        response = requests.post(
            f'{api_url}/generate_tasks',
            json=payload,
            headers=headers
        )
        response.raise_for_status()
        task = response.json()
    except requests.exceptions.HTTPError as e:
        if e.response.headers.get('content-type') == 'application/json':
            error_data = e.response.json()
            raise Exception(error_data.get('error', str(e)))
        else:
            raise e
    
    if task.get('error'):
        raise Exception(task['error'])
    
    # Poll until completion
    task = _poll(task['id'], api_url, api_key, on_progress)
    
    data_url = task.get('data_url')
    error = task.get('error')
    
    if error:
        print(f'Fabricate API returned an error: {error}')
        raise Exception(error)
    
    # Download data if not pushing to connection
    if connection is None and dest is not None and data_url is not None:
        temp_path = f'{dest}.tmp'
        
        try:
            # Download to temp location first
            _download(data_url, temp_path)
            
            if unzip and task.get('content_type') == 'application/zip':
                _unzip_file(temp_path, dest)
            else:
                # Move temp file to final destination
                Path(temp_path).rename(dest)
        finally:
            # Clean up temp file if it exists
            temp_file = Path(temp_path)
            if temp_file.exists():
                temp_file.unlink()


def _poll(
    task_id: str,
    api_url: str,
    api_key: str,
    on_progress: Optional[Callable[[Dict[str, Any]], None]] = None
) -> Dict[str, Any]:
    """
    Polls the generate task API until the task is completed.
    
    Args:
        task_id: The ID of the task to poll
        api_url: The API URL
        api_key: The API key
        on_progress: Optional progress callback
        
    Returns:
        The completed task object
        
    Raises:
        Exception: If task fails or API returns an error
    """
    headers = {'Authorization': f'Bearer {api_key}'}
    last_progress = None
    last_context = None
    
    while True:
        response = requests.get(
            f'{api_url}/generate_tasks/{task_id}',
            headers=headers
        )
        response.raise_for_status()
        task = response.json()
        
        if task.get('completed'):
            _update_progress({'progress': 100}, on_progress, last_progress, last_context)
            return task
        elif task.get('error'):
            raise Exception(task['error'])
        else:
            last_progress, last_context = _update_progress(
                task, on_progress, last_progress, last_context
            )
            time.sleep(1)


def _update_progress(
    task: Dict[str, Any],
    on_progress: Optional[Callable[[Dict[str, Any]], None]],
    last_progress: Optional[Any],
    last_context: Optional[str]
) -> tuple:
    """
    Updates progress if callback is provided and progress has changed.
    
    Args:
        task: The task object containing progress information
        on_progress: Optional progress callback
        last_progress: The last reported progress value
        last_context: The last reported context
        
    Returns:
        Tuple of (current_progress, current_context)
    """
    if not on_progress:
        return last_progress, last_context
    
    current_progress = task.get('progress')
    current_context = task.get('context')
    
    if current_progress != last_progress or current_context != last_context:
        progress_data = {
            'percentComplete': current_progress,
            'status': current_context,
            'phase': task.get('phase')
        }
        on_progress(progress_data)
        return current_progress, current_context
    
    return last_progress, last_context


def _unzip_file(zip_path: str, target_dir: str) -> None:
    """
    Unzips a file to a target directory.
    
    Args:
        zip_path: Path to the zip file
        target_dir: Target directory to extract to
    """
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(target_dir)


def _download(url: str, dest_path: str) -> None:
    """
    Downloads a file from a URL and saves it to a path.
    
    Args:
        url: The URL to download from
        dest_path: The path to save the file to
    """
    # Ensure the directory exists
    dest_file = Path(dest_path)
    dest_dir = dest_file.parent
    
    if dest_dir != Path('.'):
        # Remove directory if it exists
        if dest_dir.exists():
            shutil.rmtree(dest_dir)
        
        # Create directory
        dest_dir.mkdir(parents=True, exist_ok=True)
    
    # Download the file
    with requests.get(url, stream=True) as response:
        response.raise_for_status()
        with open(dest_path, 'wb') as f:
            for chunk in response.iter_content(chunk_size=8192):
                f.write(chunk) 